### ISSUE TITLE
500 - Internal Server Error

### ISSUE THREAD

**Issue by johnyfernandes** [chubin/rate.sx#72]
Yesterday it was working fine, couldn't use the eur.rate.sx tho! 
Now, rate.sx doesn't work :(

**Comment by chubin** [comment]
It is fixed now. Please test

**Comment by johnyfernandes** [comment]
Yes, https://rate.sx/ is working perfectly, thank you!
eur.rate.sx/btc is still not working, but not a problem.

**Comment by w1kee** [comment]
i'm getting error 500 at https://rate.sx/ again

**Comment by w1kee** [comment]
ok it's back again

**Comment by karimb** [comment]
Down. Can you fix it again please?

**Comment by Nicroxio** [comment]
> Down. Can you fix it again please?

Ditto, Internal Server Error.

**Comment by chubin** [comment]
Foxed

**Comment by danielwerg** [comment]
@chubin Hey, getting constant `500` response

**Comment by ajcryan** [comment]
same here.
